# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Leadership
  description: Leadership section
  icon: "cottage"
  tags: ["leadership"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Led by Health Centers
  description: >
    Health Care LA, IPA is a health-center-controlled Independent Physician
    Association (IPA) whose governing board is comprised of 15 c-suite leaders
    from our Federally Qualified Health Centers. This ensures that our
    leadership represents the varied and wonderful diversity of the communities
    we serve and promotes greater equity in quality care access.


    This structure also informs a culture of inclusivity that encourages and
    strengthens cooperation within our provider network.
  keyPoints:
    - icon:
        src: /images/icon-board-members.svg
        alt: image
        height: 70
        width: 70
      text: >-
        Board members are included in determining the composition of our
        network.
    - icon:
        src: /images/icon-best-practices.svg
        alt: image
        height: 70
        width: 70
      text: >-
        Our health centers share best practices and use data-driven quality
        improvement methods.
    - icon:
        src: /images/icon-quality-healthcare.svg
        alt: image
        height: 70
        width: 70
      text: >-
        We align with quality healthcare facilities that align with our
        dedication to providing better care and outcomes.
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
