# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Goal
  description: Goal Description
  icon: "cottage"
  tags: ["goal"]

# Defines the structure of this component, as well as the default values
blueprint:
  image:
    src: /images/photo-group.png
    alt: image
    width: 495
    height: 705
  title: We believe quality healthcare is a right, and easy access is a goal.
  descriptionData:
    - image:
        src: /images/Icon grow.svg
        alt: Icon grow
        width: 53
        height: 40
      boldText: ""
      description: >-
        As the managed care landscape grows ever more complex, HCLA IPA has the
        experience and agility to meet the evolving needs of our GGG centers and
        patient population, not just today but well into the future.
    - image:
        src: /images/Icon mission.svg
        alt: Icon mission
        width: 48
        height: 43
      boldText: "Our Mission:"
      description: >-
        To provide community-based providers in Los Angeles County with a
        managed, integrated healthcare delivery system to serve their
        communities in an organized, efficient, compassionate, and financially
        responsible manner.
