# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Our Impact Link
  description: Our Impact Link section
  icon: "cottage"
  tags: ["quicklink"]

# Defines the structure of this component, as well as the default values
blueprint:
  links:
    - text: Why HCLA
      link: '#Why_HCLA'
      target: _self
    - text: Strategic Goals
      link: '#Strategic_Goals'
      target: _self
    - text: Ways We Serve
      link: '#Ways_We_Serve'
      target: _self
    - text: Strength and Stability
      link: '#Strength_Stability'
      target: _self
    - text: Grants and Collaboration
      link: '#Grants_Collaboration'
      target: _self