# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Our Impact Hero
  description: Our Impact Hero section
  icon: "cottage"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: We believe that everyone deserves easy access to quality healthcare.
  image:
    src: /images/whoweare-hero.png
    alt: banner-image
    width: 550
    height: 550
    isRounded: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
