# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Latest News & Events
  description: Latest News & Events section
  icon: "cottage"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Latest News & Events
  learnMoreText: View More News
  newsData:
    - image:
        src: /images/news3.png
        alt: news image
        width: 315
        height: 210
      category: Latest News
      title: >-
        HCLA Recognized in America’s Physician Groups’ 2023 Case Studies in
        Excellence
    - image:
        src: /images/news2.png
        alt: news image
        width: 315
        height: 210
      category: Latest News
      title: HCLA Receives Grant from Cedars-Sinai
    - image:
        src: /images/news1.png
        alt: news image
        width: 315
        height: 210
      category: Latest News
      title: Gaining Ground and Supporting the Homeless

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
