# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Health Care Filter
  description: Health Care Filter Description
  icon: "cottage"
  tags: ["filter"]

# Defines the structure of this component, as well as the default values
blueprint:
  attribute1: Get Directions
  attribute2: Call
  attribute3: Fax

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
