# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Our Impact Ways We Serve
  description: Our Impact Ways We Serve section
  icon: "cottage"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  icon:
    src: /images/icon-email.svg
    alt: "Contact Icon"
    width: 40
    height: 40
  text: Email us to learn more about contracting opportunities or our white-glove approach to provider support.
  button:
    text: "Send Email"
    link: "mailto:example@example.com"
    target: "_blank"
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
