# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Our Contracted Hospitals Filter
  description: Our Contracted Hospitals Filter Description
  icon: "cottage"
  tags: ["filter"]

# Defines the structure of this component, as well as the default values
blueprint:
  plans:
    - name: Alignment Health (Formerly Citizens Choice)
      logo: /images/alignment-health-plan.png
      description: Commercial, Medi-Cal, Medicare
      phone: (866) 249-4844
      website: https://www.alignmenthealthplan.com/
    - name: Anthem Blue Cross
      logo: /images/anthem.png
      description: Commercial, Medi-Cal, Medicare
      phone: (866) 249-4844
      website: https://www.anthem.com/
    - name: Blue Shield of California
      logo: /images/blue-of-california.png
      description: Commercial, Covered California, POS
      phone: (800) 393-6130
      website: https://www.blueshieldca.com/bsca/bsc/public/member/mp/home/
    - name: Brand New Day
      logo: /images/brand-new-day.png
      description: Medicare, Medi-Medi
      phone: (866) 255-4795
      website: https://bndhmo.com/
    - name: Blue Shield of California Promise Health Plan
      logo: /images/blue-shiled-of-california.png
      description: Commercial, Covered California, POS
      phone: (800) 544-0088
      website: https://www.blueshieldca.com/bsca/bsc/wcm/connect/sites/sites_content_en/bsp/home
    - name: Central Health Medicare Plan
      logo: /images/central-health-medicare.png
      description: Medicare, Medi-Medi
      phone: (866) 314-2427
      website: https://www.centralhealthplan.com/
    - name: Cigna Health Plan
      logo: /images/cigna.png
      description: Commercial, POS
      phone: (800) 668-3813
      website: http://www.cigna.com/
    - name: Health Net
      logo: /images/health-net.png
      description: Commercial, Covered California, Medi-Cal, Medicare, POS
      phone: (877) 527-8409
      website: https://healthnet.com/
    - name: Imperial Health Plan of California
      logo: /images/imperial-health.png
      description: Medicare, Medi-Medi
      phone: (800) 838-8271
      website: http://www.imperialhealthplan.com/california/
    - name: LA Care Health Plan
      logo: /images/la-care-health.png
      description: Cal MediConnect, Covered California, Medi-Cal, Medicare
      phone: (800) 987-7521
      website: https://www.lacare.org/
    - name: Molina Health Plan
      logo: /images/molina-healthcare.png
      description: Cal MediConnect, Covered California, Medi-Cal, Medicare
      phone: (800) 987-7521
      website: http://www.molinahealthcare.com/en-us/Pages/home.aspx

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
