# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Our Impact Ways We Serve
  description: Our Impact Ways We Serve section
  icon: "cottage"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Ways We Serve
  description: >-
    HCLA IPA goes above and beyond by recognizing that accessing medical care is
    just one piece of a very complex process. Administrative and regulatory
    requirements and social determinants of health must all be addressed to
    elevate community health <strong>status</strong> and well-being.


    To that end, we provide our partner health centers with expertise, support,
    guidance, and access to administrative and technical resources, empowering
    them to remain in control of their practices while we collectively
    facilitate quality healthcare management.
  image:
    src: /images/ways-we-serve.png
    alt: ways we serve image
    width: 480
    height: 480
  greenCircleImage:
    src: /images/green-circle.svg
    alt: green circle
    width: 200
    height: 200
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
