# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Urgency Care
  description: Urgency Care
  icon: "cottage"
  tags: ["content"]

# Defines the structure of this component, as well as the default values
blueprint:
  image:
    src: /images/urgency-emergency/urgency-2.jpg
    alt: Who we are image
    width: 480
    height: 480
    isRound: true
  greenCircleImage:
    src: /images/green-circle.svg
    alt: green-circle
    width: 200
    height: 200
    isRound: true
  title: Urgent Care
  description: >-
    When you need care right away but can’t see your regular doctor, urgent care can be a good option. Urgent cares usually have shorter wait times and lower out of pocket costs than emergency rooms. Many urgent care centers are open evenings and weekends and you don’t need an appointment.
  buttonText: FIND URGENT CARE

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
