# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Clinical
  description: Clinical Description
  icon: "cottage"
  tags: ["clinical"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Curated Clinical Resources
  description: >-
    Our partner health centers consistently rank HCLA, IPA above the competition
    for our white-glove approach to pulling together the optimal mix of
    informational, educational, technological, and operational resources needed
    to excel within a value-based healthcare system, including:
  detailSection1:
    description: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod
      tempo.
    buttonText: Partner Health Center Login
  detailSection2:
    description: >-
      Learn more about contracting opportunities or our white-glove approach to
      provider support.
    buttonText: Learn More
  points:
    - Cozeva
    - Clinical, Quality, and Operational Support Staff
    - MedPOINT Management Provider Portalf
    - Lanes Health Information Exchange
    - Secure, Individualized FTP
    - Partners in Care
    - Innovacer
    - Samaritan City
