# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Callout
  description: Callout section
  icon: "cottage"
  tags: ["quicklink"]

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Call 911 for life threatening emergencies."
  icon: "/images/icon-911.svg"
