# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Emergency Care
  description: Emergency Care Description
  icon: "cottage"
  tags: ["emergency"]

# Defines the structure of this component, as well as the default values
blueprint:
    title: An emergency medical condition can consist of one or more of the following symptoms
    detailSection1:
      description: >-
        Call 911 if your condition is Life threatening.
    points:
      - Difficulty breathing, shortness of breath
      - Chest pain/pressure
      - Fainting, trouble talking, dizziness
      - Changes in vision
      - Confusion
      - Uncontrolled bleeding
      - Severe persistent vomiting or diarrhea
      - Coughing up or vomiting blood
      - Suicidal feelings
      - Unusual abdominal pain
      - Suspected broken bones
      - Eye pressure
      - Asthma attack
    points2:
      - icon:
          src: /images/icon-check.svg
          alt: check icon
          width: 35
          height: 35
        title:
        description: >-
          <strong>When should I call the Doctor for advice?</strong>
          <br/>You can always call your doctor’s office for advice. Especially for conditions such as: fevers over 102.0, headaches, heartburn, indigestion, constipation, hemorrhoids or back pain. If you call your doctor’s office after working hours, you may ask to speak with the doctor on call.
      - icon:
          src: /images/icon-check.svg
          alt: check icon
          width: 35
          height: 35
        title:
        description: >-
          <strong>What should I do if my Doctor’s office can’t help me?</strong>
          <br/> Contact your health plan’s 24-hour nurse advice line.
          <strong>Click here</strong> for a list of nurse advice lines by health plan.