# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Clinical
  description: Clinical Description
  icon: "cottage"
  tags: ["clinical"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Featured Clinical Resources
  description: >-
    Our partner health centers consistently rank HCLA, IPA above the competition
    for our white-glove approach to pulling together the optimal mix of
    informational, educational, technological, and operational resources needed
    to excel within a value-based healthcare system, including:
  points:
    - name: HEDIS Measure Information
      link: https://healthcarela.org/wp-content/uploads/2016/12/Heidis-Tip-Sheet-Flyer-_2-pages.pdf
    - name: STARs Program
      link: https://healthcarela.org/wp-content/uploads/2016/12/CMS-STARS-Rating-System-Overview-3.doc
    - name: ICD 10
      link: https://healthcarela.org/wp-content/uploads/2016/12/Resources-ICD101.docx
    - name: Authorizations
      link: https://healthcarela.org/wp-content/uploads/2016/12/HCLA-Full-Auth-Requests-Form.doc
    - name: Direct Referrals
      link: https://healthcarela.org/wp-content/uploads/2016/12/HCLA-Direct-Referral-Form.doc