# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Our Impact Hero
  description: Our Impact Hero section
  icon: "cottage"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Our Strategic Goals
  goals:
    - icon:
        src: /images/icon-quality.svg
        alt: quality icon
        width: 50
        height: 50
      title:
      description: >-
        Deliver high-quality, cost-efficient care through measuring and
        monitoring performance standards, and providing training and support to
        meet best practice standards and quality benchmarks.
    - icon:
        src: /images/icon-collaborate.svg
        alt: collaborate icon
        width: 50
        height: 50
      title:
      description: >-
        Become the IPA of choice for government-sponsored programs by
        cultivating strong, collaborative relationships with health plans,
        health centers, industry stakeholders, and state and federal
        decision-makers.
    - icon:
        src: /images/icon-fulfill.svg
        alt: fulfill icon
        width: 50
        height: 50
      title:
      description: >-
        Fulfill the Healthcare <strong>Quintuple Aim</strong> of reducing costs
        while also improving population health, patient experience,
        <strong>Health Equity</strong> and team well-being by improving health
        outcomes for high-risk populations, strengthening infrastructure and
        operations, diversifying funding streams, and expanding partnerships and
        business relationships.
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
