# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Providers Secure Meeting
  description: Providers Secure Meeting Description
  icon: "cottage"
  tags: ["support"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: We Support and Collaborate with Stable Medical Homes
  description: >-
    Open communication and transparency help to keep our network inclusive and connected.
    We invite you to join us at various upcoming board and IPA meetings, and to be an active voice in the HCLA IPA family.
