# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Our Impact Ways We Serve
  description: Our Impact Ways We Serve section
  icon: "cottage"
  tags: ["hero"]

# Defines the structure of this component, as well as the default values
blueprint:
  title: Benefits of Network Membership
  isLargeTitle: true
  points:
    - icon:
        src: /images/icon-trusted.svg
        alt: trusted icon
        width: 35
        height: 35
        hasBackground: true
      title: Trusted Network
      description: Deliver high-quality, cost-efficient care through measuring and monitoring performance standards, and providing training and support to meet best practice standards and quality benchmarks.
    - icon:
        src: /images/icon-better-selections.svg
        alt: better selections icon
        width: 35
        height: 35
        hasBackground: true
      title: Better Selection
      description: HCLA IPA contracts with most major managed care health plans serving Medi-Cal, Medicare Advantage, Covered California, Cal MediConnect, and commercial members. Our range of health plan choices makes it easier for your patients and their families to stay within their chosen health center if their insurance ever changes
    - icon:
        src: /images/icon-stability.svg
        alt: stability icon
        width: 35
        height: 35
        hasBackground: true
      title: Proven Stability
      description: Our IPA has served LA County providers and patients for over 25 years. We help guide and anchor patient care with the community health centers they know and trust.
    - icon:
        src: /images/icon-culturally.svg
        alt: culturally icon
        width: 35
        height: 35
        hasBackground: true
      title: Culturally Sensitive
      description: HCLA IPA is as diverse as the communities we serve. Our multi-lingual, multi-cultural network embraces all of Los Angeles County.
    - icon:
        src: /images/icon-reputation.svg
        alt: reputation icon
        width: 35
        height: 35
        hasBackground: true
      title: Reputation
      description: HCLA IPA is consistently ranked above the competition by providers and industry leaders for our white-glove approach and dedication to supporting quality, accessible health care to the patients and communities who need it most.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
