# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Callout
  description: Callout section
  icon: "cottage"
  tags: ["quicklink"]

# Defines the structure of this component, as well as the default values
blueprint:
  icon: "/images/greencall-icon.svg"
  message: "If you need to check on a referral, need help finding a local provider, or if you have questions, please call our customer service department at"
  contactInfo: "818-702-0100,"
  contactLink: 8187020100
  operatingHours: "M – F 9:00 a.m. – 5:00 p.m. PST."